<template>
<div class="content">
<h1>Datenschutzerkl&auml;rung</h1>
<h2>Einleitung</h2>
<p>Mit der folgenden Datenschutzerkl&auml;rung m&ouml;chten wir Sie dar&uuml;ber aufkl&auml;ren, welche Arten Ihrer personenbezogenen Daten (nachfolgend auch kurz als "Daten" bezeichnet) wir zu welchen Zwecken und in welchem Umfang verarbeiten. Die Datenschutzerkl&auml;rung gilt f&uuml;r alle von uns durchgef&uuml;hrten Verarbeitungen personenbezogener Daten, sowohl im Rahmen der Erbringung unserer Leistungen als auch insbesondere auf unseren Webseiten, in mobilen Applikationen sowie innerhalb externer Onlinepr&auml;senzen, wie z.B. unserer Social-Media-Profile (nachfolgend zusammenfassend bezeichnet als "Onlineangebot").</p>
<p>Die verwendeten Begriffe sind nicht geschlechtsspezifisch.</p>
<p>Stand: 22. M&auml;rz 2020</p>
<h2>Verantwortlicher</h2>
<p>Patrick R&ouml;vekamp</p>
<p>Jakoberstr. 70</p>
<p>86152 Augsburg</p>
<p>Deutschland</p>
<p>E-Mail-Adresse: info@corona-compass.org</p>
<p>Impressum: www.corona-compass.org</p>
<h2>&Uuml;bersicht der Verarbeitungen</h2>
<p>Die nachfolgende &Uuml;bersicht fasst die Arten der verarbeiteten Daten und die Zwecke ihrer Verarbeitung zusammen und verweist auf die betroffenen Personen.</p>
<h3>Arten der verarbeiteten Daten</h3>
<ul>
<li>Bestandsdaten (z.B. Namen, Adressen).</li>
<li>Inhaltsdaten (z.B. Texteingaben, Fotografien, Videos).</li>
<li>Kontaktdaten (z.B. E-Mail, Telefonnummern).</li>
<li>Meta-/Kommunikationsdaten (z.B. Ger&auml;te-Informationen, IP-Adressen).</li>
<li>Nutzungsdaten (z.B. besuchte Webseiten, Interesse an Inhalten, Zugriffszeiten).</li>
</ul>
<h3>Kategorien betroffener Personen</h3>
<ul>
<li>Interessenten.</li>
<li>Kommunikationspartner.</li>
<li>Nutzer (z.B. Webseitenbesucher, Nutzer von Onlinediensten).</li>
</ul>
<h3>Zwecke der Verarbeitung</h3>
<ul>
<li>Bereitstellung unseres Onlineangebotes und Nutzerfreundlichkeit.</li>
<li>Besuchsaktionsauswertung.</li>
<li>Direktmarketing (z.B. per E-Mail oder postalisch).</li>
<li>Interessenbasiertes und verhaltensbezogenes Marketing.</li>
<li>Kontaktanfragen und Kommunikation.</li>
<li>Konversionsmessung (Messung der Effektivit&auml;t von Marketingma&szlig;nahmen).</li>
<li>Profiling (Erstellen von Nutzerprofilen).</li>
<li>Remarketing.</li>
<li>Reichweitenmessung (z.B. Zugriffsstatistiken, Erkennung wiederkehrender Besucher).</li>
<li>Sicherheitsma&szlig;nahmen.</li>
<li>Tracking (z.B. interessens-/verhaltensbezogenes Profiling, Nutzung von Cookies).</li>
<li>Vertragliche Leistungen und Service.</li>
<li>Verwaltung und Beantwortung von Anfragen.</li>
</ul>
<h3>Ma&szlig;gebliche Rechtsgrundlagen</h3>
<p>Im Folgenden teilen wir die Rechtsgrundlagen der Datenschutzgrundverordnung (DSGVO), auf deren Basis wir die personenbezogenen Daten verarbeiten, mit. Bitte beachten Sie, dass zus&auml;tzlich zu den Regelungen der DSGVO die nationalen Datenschutzvorgaben in Ihrem bzw. unserem Wohn- und Sitzland gelten k&ouml;nnen. Sollten ferner im Einzelfall speziellere Rechtsgrundlagen ma&szlig;geblich sein, teilen wir Ihnen diese in der Datenschutzerkl&auml;rung mit.</p>
<ul>
<li>Einwilligung (Art. 6 Abs. 1 S. 1 lit. a DSGVO)&nbsp;- Die betroffene Person hat ihre Einwilligung in die Verarbeitung der sie betreffenden personenbezogenen Daten f&uuml;r einen spezifischen Zweck oder mehrere bestimmte Zwecke gegeben.</li>
<li>Vertragserf&uuml;llung und vorvertragliche Anfragen (Art. 6 Abs. 1 S. 1 lit. b. DSGVO)&nbsp;- Die Verarbeitung ist f&uuml;r die Erf&uuml;llung eines Vertrags, dessen Vertragspartei die betroffene Person ist, oder zur Durchf&uuml;hrung vorvertraglicher Ma&szlig;nahmen erforderlich, die auf Anfrage der betroffenen Person erfolgen.</li>
<li>Berechtigte Interessen (Art. 6 Abs. 1 S. 1 lit. f.&nbsp;DSGVO)&nbsp;- Die Verarbeitung ist zur Wahrung der berechtigten Interessen des Verantwortlichen oder eines Dritten erforderlich, sofern nicht die Interessen oder Grundrechte und Grundfreiheiten der betroffenen Person, die den Schutz personenbezogener Daten erfordern, &uuml;berwiegen.</li>
</ul>
<p>Nationale Datenschutzregelungen in Deutschland: Zus&auml;tzlich zu den Datenschutzregelungen der Datenschutz-Grundverordnung gelten nationale Regelungen zum Datenschutz in Deutschland. Hierzu geh&ouml;rt insbesondere das Gesetz zum Schutz vor Missbrauch personenbezogener Daten bei der Datenverarbeitung (Bundesdatenschutzgesetz &ndash; BDSG). Das BDSG enth&auml;lt insbesondere Spezialregelungen zum Recht auf Auskunft, zum Recht auf L&ouml;schung, zum Widerspruchsrecht, zur Verarbeitung besonderer Kategorien personenbezogener Daten, zur Verarbeitung f&uuml;r andere Zwecke und zur &Uuml;bermittlung sowie automatisierten Entscheidungsfindung im Einzelfall einschlie&szlig;lich Profiling. Des Weiteren regelt es die Datenverarbeitung f&uuml;r Zwecke des Besch&auml;ftigungsverh&auml;ltnisses (&sect; 26 BDSG), insbesondere im Hinblick auf die Begr&uuml;ndung, Durchf&uuml;hrung oder Beendigung von Besch&auml;ftigungsverh&auml;ltnissen sowie die Einwilligung von Besch&auml;ftigten. Ferner k&ouml;nnen Landesdatenschutzgesetze der einzelnen Bundesl&auml;nder zur Anwendung gelangen.</p>
<h2>&Uuml;bermittlung und Offenbarung von personenbezogenen Daten</h2>
<p>Im Rahmen unserer Verarbeitung von personenbezogenen Daten kommt es vor, dass die Daten an andere Stellen, Unternehmen, rechtlich selbstst&auml;ndige Organisationseinheiten oder Personen &uuml;bermittelt oder sie ihnen gegen&uuml;ber offengelegt werden. Zu den Empf&auml;ngern dieser Daten k&ouml;nnen z.B. Zahlungsinstitute im Rahmen von Zahlungsvorg&auml;ngen, mit IT-Aufgaben beauftragte Dienstleister oder Anbieter von Diensten und Inhalten, die in eine Webseite eingebunden werden, geh&ouml;ren. In solchen Fall beachten wir die gesetzlichen Vorgaben und schlie&szlig;en insbesondere entsprechende Vertr&auml;ge bzw. Vereinbarungen, die dem Schutz Ihrer Daten dienen, mit den Empf&auml;ngern Ihrer Daten ab.</p>
<h2>Einsatz von Cookies</h2>
<p>Cookies sind Textdateien, die Daten von besuchten Websites oder Domains enthalten und von einem Browser auf dem Computer des Benutzers gespeichert werden. Ein Cookie dient in erster Linie dazu, die Informationen &uuml;ber einen Benutzer w&auml;hrend oder nach seinem Besuch innerhalb eines Onlineangebotes zu speichern. Zu den gespeicherten Angaben k&ouml;nnen z.B. die Spracheinstellungen auf einer Webseite, der Loginstatus, ein Warenkorb oder die Stelle, an der ein Video geschaut wurde, geh&ouml;ren. Zu dem Begriff der Cookies z&auml;hlen wir ferner andere Technologien, die die gleichen Funktionen wie Cookies erf&uuml;llen (z.B., wenn Angaben der Nutzer anhand pseudonymer Onlinekennzeichnungen gespeichert werden, auch als "Nutzer-IDs" bezeichnet)</p>
<p>Die folgenden Cookie-Typen und Funktionen werden unterschieden:</p>
<ul>
<li>Tempor&auml;re Cookies (auch: Session- oder Sitzungs-Cookies):&nbsp;Tempor&auml;re Cookies werden sp&auml;testens gel&ouml;scht, nachdem ein Nutzer ein Online-Angebot verlassen und seinen Browser geschlossen hat.</li>
<li>Permanente Cookies:&nbsp;Permanente Cookies bleiben auch nach dem Schlie&szlig;en des Browsers gespeichert. So kann beispielsweise der Login-Status gespeichert oder bevorzugte Inhalte direkt angezeigt werden, wenn der Nutzer eine Website erneut besucht. Ebenso k&ouml;nnen die Interessen von Nutzern, die zur Reichweitenmessung oder zu Marketingzwecken verwendet werden, in einem solchen Cookie gespeichert werden.</li>
<li>First-Party-Cookies:&nbsp;First-Party-Cookies werden von uns selbst gesetzt.</li>
<li>Third-Party-Cookies (auch: Drittanbieter-Cookies): Drittanbieter-Cookies werden haupts&auml;chlich von Werbetreibenden (sog. Dritten) verwendet, um Benutzerinformationen zu verarbeiten.</li>
<li>Notwendige (auch: essentielle oder unbedingt erforderliche) Cookies:Cookies k&ouml;nnen zum einen f&uuml;r den Betrieb einer Webseite unbedingt erforderlich sein (z.B. um Logins oder andere Nutzereingaben zu speichern oder aus Gr&uuml;nden der Sicherheit).</li>
<li>Statistik-, Marketing- und Personalisierungs-Cookies: Ferner werden Cookies im Regelfall auch im Rahmen der Reichweitenmessung eingesetzt sowie dann, wenn die Interessen eines Nutzers oder sein Verhalten (z.B. Betrachten bestimmter Inhalte, Nutzen von Funktionen etc.) auf einzelnen Webseiten in einem Nutzerprofil gespeichert werden. Solche Profile dienen dazu, den Nutzern z.B. Inhalte anzuzeigen, die ihren potentiellen Interessen entsprechen. Dieses Verfahren wird auch als "Tracking", d.h., Nachverfolgung der potentiellen Interessen der Nutzer bezeichnet. . Soweit wir Cookies oder "Tracking"-Technologien einsetzen, informieren wir Sie gesondert in unserer Datenschutzerkl&auml;rung oder im Rahmen der Einholung einer Einwilligung.</li>
</ul>
<p>Hinweise zu Rechtsgrundlagen:Auf welcher Rechtsgrundlage wir Ihre personenbezogenen Daten mit Hilfe von Cookies verarbeiten, h&auml;ngt davon ab, ob wir Sie um eine Einwilligung bitten. Falls dies zutrifft und Sie in die Nutzung von Cookies einwilligen, ist die Rechtsgrundlage der Verarbeitung Ihrer Daten die erkl&auml;rte Einwilligung. Andernfalls werden die mithilfe von Cookies verarbeiteten Daten auf Grundlage unserer berechtigten Interessen (z.B. an einem betriebswirtschaftlichen Betrieb unseres Onlineangebotes und dessen Verbesserung) verarbeitet oder, wenn der Einsatz von Cookies erforderlich ist, um unsere vertraglichen Verpflichtungen zu erf&uuml;llen.</p>
<p>Allgemeine Hinweise zum Widerruf und Widerspruch (Opt-Out):Abh&auml;ngig davon, ob die Verarbeitung auf Grundlage einer Einwilligung oder gesetzlichen Erlaubnis erfolgt, haben Sie jederzeit die M&ouml;glichkeit, eine erteilte Einwilligung zu widerrufen oder der Verarbeitung Ihrer Daten durch Cookie-Technologien zu widersprechen (zusammenfassend als "Opt-Out" bezeichnet). Sie k&ouml;nnen Ihren Widerspruch zun&auml;chst mittels der Einstellungen Ihres Browsers erkl&auml;ren, z.B., indem Sie die Nutzung von Cookies deaktivieren (wobei hierdurch auch die Funktionsf&auml;higkeit unseres Onlineangebotes eingeschr&auml;nkt werden kann). Ein Widerspruch gegen den Einsatz von Cookies zu Zwecken des Onlinemarketings kann auch mittels einer Vielzahl von Diensten, vor allem im Fall des Trackings, &uuml;ber die Webseiten <a href="https://www.google.com/url?q=https://optout.aboutads.info/&amp;sa=D&amp;ust=1584885756531000">https://optout.aboutads.info</a>&nbsp;und<a href="https://www.google.com/url?q=https://www.youronlinechoices.com/&amp;sa=D&amp;ust=1584885756531000">https://www.youronlinechoices.com/</a>&nbsp;erkl&auml;rt werden. Daneben k&ouml;nnen Sie weitere Widerspruchshinweise im Rahmen der Angaben zu den eingesetzten Dienstleistern und Cookies erhalten.</p>
<p>Verarbeitung von Cookie-Daten auf Grundlage einer Einwilligung: Bevor wir Daten im Rahmen der Nutzung von Cookies verarbeiten oder verarbeiten lassen, bitten wir die Nutzer um eine jederzeit widerrufbare Einwilligung. Bevor die Einwilligung nicht ausgesprochen wurde, werden allenfalls Cookies eingesetzt, die f&uuml;r den Betrieb unseres Onlineangebotes erforderlich sind. Deren Einsatz erfolgt auf der Grundlage unseres Interesses und des Interesses der Nutzer an der erwarteten Funktionsf&auml;higkeit unseres Onlineangebotes.</p>
<ul>
<li>Verarbeitete Datenarten:&nbsp;Nutzungsdaten (z.B. besuchte Webseiten, Interesse an Inhalten, Zugriffszeiten), Meta-/Kommunikationsdaten (z.B. Ger&auml;te-Informationen, IP-Adressen).</li>
<li>Betroffene Personen:&nbsp;Nutzer (z.B. Webseitenbesucher, Nutzer von Onlinediensten).</li>
<li>Rechtsgrundlagen:&nbsp;Einwilligung (Art. 6 Abs. 1 S. 1 lit. a DSGVO), Berechtigte Interessen (Art. 6 Abs. 1 S. 1 lit. f. DSGVO).</li>
</ul>
<h2>Bereitstellung des Onlineangebotes und Webhosting</h2>
<p>Um unser Onlineangebot sicher und effizient bereitstellen zu k&ouml;nnen, nehmen wir die Leistungen von einem oder mehreren Webhosting-Anbietern in Anspruch, von deren Servern (bzw. von ihnen verwalteten Servern) das Onlineangebot abgerufen werden kann. Zu diesen Zwecken k&ouml;nnen wir Infrastruktur- und Plattformdienstleistungen, Rechenkapazit&auml;t, Speicherplatz und Datenbankdienste sowie Sicherheitsleistungen und technische Wartungsleistungen in Anspruch nehmen.</p>
<p>Zu den im Rahmen der Bereitstellung des Hostingangebotes verarbeiteten Daten k&ouml;nnen alle die Nutzer unseres Onlineangebotes betreffenden Angaben geh&ouml;ren, die im Rahmen der Nutzung und der Kommunikation anfallen. Hierzu geh&ouml;ren regelm&auml;&szlig;ig die IP-Adresse, die notwendig ist, um die Inhalte von Onlineangeboten an Browser ausliefern zu k&ouml;nnen, und alle innerhalb unseres Onlineangebotes oder von Webseiten get&auml;tigten Eingaben.</p>
<p>Erhebung von Zugriffsdaten und Logfiles: Wir selbst (bzw. unser Webhostinganbieter) erheben Daten zu jedem Zugriff auf den Server (sogenannte Serverlogfiles). Zu den Serverlogfiles k&ouml;nnen die Adresse und Name der abgerufenen Webseiten und Dateien, Datum und Uhrzeit des Abrufs, &uuml;bertragene Datenmengen, Meldung &uuml;ber erfolgreichen Abruf, Browsertyp nebst Version, das Betriebssystem des Nutzers, Referrer URL (die zuvor besuchte Seite) und im Regelfall IP-Adressen und der anfragende Provider geh&ouml;ren.</p>
<p>Die Serverlogfiles k&ouml;nnen zum einen zu Zwecken der Sicherheit eingesetzt werden, z.B., um eine &Uuml;berlastung der Server zu vermeiden (insbesondere im Fall von missbr&auml;uchlichen Angriffen, sogenannten DDoS-Attacken) und zum anderen, um die Auslastung der Server und ihre Stabilit&auml;t sicherzustellen.</p>
<ul>
<li>Verarbeitete Datenarten:&nbsp;Inhaltsdaten (z.B. Texteingaben, Fotografien, Videos), Nutzungsdaten (z.B. besuchte Webseiten, Interesse an Inhalten, Zugriffszeiten), Meta-/Kommunikationsdaten (z.B. Ger&auml;te-Informationen, IP-Adressen).</li>
<li>Betroffene Personen:&nbsp;Nutzer (z.B. Webseitenbesucher, Nutzer von Onlinediensten).</li>
<li>Rechtsgrundlagen:&nbsp;Berechtigte Interessen (Art. 6 Abs. 1 S. 1 lit. f.&nbsp;DSGVO).</li>
</ul>
<h2>Webanalyse und Optimierung</h2>
<p>Die Webanalyse (auch als "Reichweitenmessung" bezeichnet) dient der Auswertung der Besucherstr&ouml;me unseres Onlineangebotes und kann Verhalten, Interessen oder demographische Informationen zu den Besuchern, wie z.B. das Alter oder das Geschlecht, als pseudonyme Werte umfassen. Mit Hilfe der Reichweitenanalyse k&ouml;nnen wir z.B. erkennen, zu welcher Zeit unser Onlineangebot oder dessen Funktionen oder Inhalte am h&auml;ufigsten genutzt werden oder zur Wiederverwendung einladen. Ebenso k&ouml;nnen wir nachvollziehen, welche Bereiche der Optimierung bed&uuml;rfen.</p>
<p>Neben der Webanalyse k&ouml;nnen wir auch Testverfahren einsetzen, um z.B. unterschiedliche Versionen unseres Onlineangebotes oder seiner Bestandteile zu testen und optimieren.</p>
<p>Zu diesen Zwecken k&ouml;nnen sogenannte Nutzerprofile angelegt und in einer Datei (sogenannte "Cookie") gespeichert oder &auml;hnliche Verfahren mit dem gleichen Zweck genutzt werden. Zu diesen Angaben k&ouml;nnen z.B. betrachtete Inhalte, besuchte Webseiten und dort genutzte Elemente und technische Angaben, wie der verwendete Browser, das verwendete Computersystem sowie Angaben zu Nutzungszeiten geh&ouml;ren. Sofern Nutzer in die Erhebung ihrer Standortdaten eingewilligt haben, k&ouml;nnen je nach Anbieter auch diese verarbeitet werden.</p>
<p>Es werden ebenfalls die IP-Adressen der Nutzer gespeichert. Jedoch nutzen wir ein IP-Masking-Verfahren (d.h., Pseudonymisierung durch K&uuml;rzung der IP-Adresse) zum Schutz der Nutzer. Generell werden die im Rahmen von Webanalyse, A/B-Testings und Optimierung keine Klardaten der Nutzer (wie z.B. E-Mail-Adressen oder Namen) gespeichert, sondern Pseudonyme. D.h., wir als auch die Anbieter der eingesetzten Software kennen nicht die tats&auml;chliche Identit&auml;t der Nutzer, sondern nur den f&uuml;r Zwecke der jeweiligen Verfahren in deren Profilen gespeicherten Angaben.</p>
<p>Hinweise zu Rechtsgrundlagen:&nbsp;Sofern wir die Nutzer um deren Einwilligung in den Einsatz der Drittanbieter bitten, ist die Rechtsgrundlage der Verarbeitung von Daten die Einwilligung. Ansonsten werden die Daten der Nutzer auf Grundlage unserer berechtigten Interessen (d.h. Interesse an effizienten, wirtschaftlichen und empf&auml;ngerfreundlichen Leistungen) verarbeitet. In diesem Zusammenhang m&ouml;chten wir Sie auch auf die Informationen zur Verwendung von Cookies in dieser Datenschutzerkl&auml;rung hinweisen.</p>
<ul>
<li>Betroffene Personen:&nbsp;Nutzer (z.B. Webseitenbesucher, Nutzer von Onlinediensten).</li>
<li>Zwecke der Verarbeitung:&nbsp;Reichweitenmessung (z.B. Zugriffsstatistiken, Erkennung wiederkehrender Besucher), Tracking (z.B. interessens-/verhaltensbezogenes Profiling, Nutzung von Cookies), Besuchsaktionsauswertung, Profiling (Erstellen von Nutzerprofilen).</li>
<li>Sicherheitsma&szlig;nahmen:&nbsp;IP-Masking (Pseudonymisierung der IP-Adresse).</li>
<li>Rechtsgrundlagen:&nbsp;Einwilligung (Art. 6 Abs. 1 S. 1 lit. a DSGVO), Berechtigte Interessen (Art. 6 Abs. 1 S. 1 lit. f. DSGVO).</li>
</ul>
<h2>Onlinemarketing</h2>
<p>Wir verarbeiten personenbezogene Daten zu Zwecken des Onlinemarketings, worunter insbesondere die Vermarktung von Werbefl&auml;chen oder Darstellung von werbenden und sonstigen Inhalten (zusammenfassend als "Inhalte" bezeichnet) anhand potentieller Interessen der Nutzer sowie die Messung ihrer Effektivit&auml;t fallen kann.</p>
<p>Zu diesen Zwecken werden sogenannte Nutzerprofile angelegt und in einer Datei (sogenannte "Cookie") gespeichert oder &auml;hnliche Verfahren genutzt, mittels derer die f&uuml;r die Darstellung der vorgenannten Inhalte relevante Angaben zum Nutzer gespeichert werden. Zu diesen Angaben k&ouml;nnen z.B. betrachtete Inhalte, besuchte Webseiten, genutzte Onlinenetzwerke, aber auch Kommunikationspartner und technische Angaben, wie der verwendete Browser, das verwendete Computersystem sowie Angaben zu Nutzungszeiten geh&ouml;ren. Sofern Nutzer in die Erhebung ihrer Standortdaten eingewilligt haben, k&ouml;nnen auch diese verarbeitet werden.</p>
<p>Es werden ebenfalls die IP-Adressen der Nutzer gespeichert. Jedoch nutzen wir zur Verf&uuml;gung stehende IP-Masking-Verfahren (d.h., Pseudonymisierung durch K&uuml;rzung der IP-Adresse) zum Schutz der Nutzer. Generell werden im Rahmen des Onlinemarketingverfahren keine Klardaten der Nutzer (wie z.B. E-Mail-Adressen oder Namen) gespeichert, sondern Pseudonyme. D.h., wir als auch die Anbieter der Onlinemarketingverfahren kennen nicht die tats&auml;chlich Identit&auml;t der Nutzer, sondern nur die in deren Profilen gespeicherten Angaben.</p>
<p>Die Angaben in den Profilen werden im Regelfall in den Cookies oder mittels &auml;hnlicher Verfahren gespeichert. Diese Cookies k&ouml;nnen sp&auml;ter generell auch auf anderen Webseiten die dasselbe Onlinemarketingverfahren einsetzen, ausgelesen und zu Zwecken der Darstellung von Inhalten analysiert als auch mit weiteren Daten erg&auml;nzt und auf dem Server des Onlinemarketingverfahrensanbieters gespeichert werden.</p>
<p>Ausnahmsweise k&ouml;nnen Klardaten den Profilen zugeordnet werden. Das ist der Fall, wenn die Nutzer z.B. Mitglieder eines sozialen Netzwerks sind, dessen Onlinemarketingverfahren wir einsetzen und das Netzwerk die Profile der Nutzer mit den vorgenannten Angaben verbindet. Wir bitten darum, zu beachten, dass Nutzer mit den Anbietern zus&auml;tzliche Abreden, z.B. durch Einwilligung im Rahmen der Registrierung, treffen k&ouml;nnen.</p>
<p>Wir erhalten grunds&auml;tzlich nur Zugang zu zusammengefassten Informationen &uuml;ber den Erfolg unserer Werbeanzeigen. Jedoch k&ouml;nnen wir im Rahmen sogenannter Konversionsmessungen pr&uuml;fen, welche unserer Onlinemarketingverfahren zu einer sogenannten Konversion gef&uuml;hrt haben, d.h. z.B., zu einem Vertragsschluss mit uns. Die Konversionsmessung wird alleine zur Analyse des Erfolgs unserer Marketingma&szlig;nahmen verwendet.</p>
<p>Solange nicht anders angegeben, bitten wir Sie davon auszugehen, dass verwendete Cookies f&uuml;r einen Zeitraum von zwei Jahren gespeichert werden.</p>
<p>Hinweise zu Rechtsgrundlagen:&nbsp;Sofern wir die Nutzer um deren Einwilligung in den Einsatz der Drittanbieter bitten, ist die Rechtsgrundlage der Verarbeitung von Daten die Einwilligung. Ansonsten werden die Daten der Nutzer auf Grundlage unserer berechtigten Interessen (d.h. Interesse an effizienten, wirtschaftlichen und empf&auml;ngerfreundlichen Leistungen) verarbeitet. In diesem Zusammenhang m&ouml;chten wir Sie auch auf die Informationen zur Verwendung von Cookies in dieser Datenschutzerkl&auml;rung hinweisen.</p>
<ul>
<li>Verarbeitete Datenarten:&nbsp;Nutzungsdaten (z.B. besuchte Webseiten, Interesse an Inhalten, Zugriffszeiten), Meta-/Kommunikationsdaten (z.B. Ger&auml;te-Informationen, IP-Adressen).</li>
<li>Betroffene Personen:&nbsp;Nutzer (z.B. Webseitenbesucher, Nutzer von Onlinediensten), Interessenten.</li>
<li>Zwecke der Verarbeitung:&nbsp;Tracking (z.B. interessens-/verhaltensbezogenes Profiling, Nutzung von Cookies), Remarketing, Besuchsaktionsauswertung, Interessenbasiertes und verhaltensbezogenes Marketing, Profiling (Erstellen von Nutzerprofilen), Konversionsmessung (Messung der Effektivit&auml;t von Marketingma&szlig;nahmen), Reichweitenmessung (z.B. Zugriffsstatistiken, Erkennung wiederkehrender Besucher).</li>
<li>Sicherheitsma&szlig;nahmen:&nbsp;IP-Masking (Pseudonymisierung der IP-Adresse).</li>
<li>Rechtsgrundlagen:&nbsp;Einwilligung (Art. 6 Abs. 1 S. 1 lit. a DSGVO), Berechtigte Interessen (Art. 6 Abs. 1 S. 1 lit. f. DSGVO).</li>
<li>Widerspruchsm&ouml;glichkeit (Opt-Out):&nbsp;Wir verweisen auf die Datenschutzhinweise der jeweiligen Anbieter und die zu den Anbietern angegebenen Widerspruchsm&ouml;glichkeiten (sog. \"Opt-Out\"). Sofern keine explizite Opt-Out-M&ouml;glichkeit angegeben wurde, besteht zum einen die M&ouml;glichkeit, dass Sie Cookies in den Einstellungen Ihres Browsers abschalten. Hierdurch k&ouml;nnen jedoch Funktionen unseres Onlineangebotes eingeschr&auml;nkt werden. Wir empfehlen daher zus&auml;tzlich die folgenden Opt-Out-M&ouml;glichkeiten, die zusammenfassend auf jeweilige Gebiete gerichtet angeboten werden: a) Europa:<a href="https://www.google.com/url?q=https://www.youronlinechoices.eu/&amp;sa=D&amp;ust=1584885756539000">https://www.youronlinechoices.eu</a>. b) Kanada:<a href="https://www.google.com/url?q=https://www.youradchoices.ca/choices&amp;sa=D&amp;ust=1584885756539000">https://www.youradchoices.ca/choices</a>. c) USA:<a href="https://www.google.com/url?q=https://www.aboutads.info/choices&amp;sa=D&amp;ust=1584885756540000">https://www.aboutads.info/choices</a>. d) Gebiets&uuml;bergreifend:<a href="https://www.google.com/url?q=https://optout.aboutads.info/&amp;sa=D&amp;ust=1584885756540000">https://optout.aboutads.info</a>.</li>
</ul>
<p>Eingesetzte Dienste und Diensteanbieter:</p>
<ul>
<li>Google Analytics:&nbsp;Onlinemarketing und Webanalyse; Dienstanbieter: Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Irland, Mutterunternehmen: Google LLC, 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA; Website:<a href="https://www.google.com/url?q=https://marketingplatform.google.com/intl/de/about/analytics/&amp;sa=D&amp;ust=1584885756541000">https://marketingplatform.google.com/intl/de/about/analytics/</a>; Datenschutzerkl&auml;rung:<a href="https://www.google.com/url?q=https://policies.google.com/privacy&amp;sa=D&amp;ust=1584885756541000">https://policies.google.com/privacy</a>; Privacy Shield (Gew&auml;hrleistung Datenschutzniveau bei Verarbeitung von Daten in den USA):<a href="https://www.google.com/url?q=https://www.privacyshield.gov/participant?id%3Da2zt000000001L5AAI%26status%3DActive&amp;sa=D&amp;ust=1584885756541000">https://www.privacyshield.gov/participant?id=a2zt000000001L5AAI&amp;status=Active</a>; Widerspruchsm&ouml;glichkeit (Opt-Out): Opt-Out-Plugin:<a href="https://www.google.com/url?q=https://tools.google.com/dlpage/gaoptout?hl%3Dde&amp;sa=D&amp;ust=1584885756542000">https://tools.google.com/dlpage/gaoptout?hl=de</a>, Einstellungen f&uuml;r die Darstellung von Werbeeinblendungen:<a href="https://www.google.com/url?q=https://adssettings.google.com/authenticated&amp;sa=D&amp;ust=1584885756542000">https://adssettings.google.com/authenticated</a>.</li>
</ul>
<h2>Pr&auml;senzen in sozialen Netzwerken</h2>
<p>Wir unterhalten Onlinepr&auml;senzen innerhalb sozialer Netzwerke und verarbeiten in diesem Rahmen Daten der Nutzer, um mit den dort aktiven Nutzern zu kommunizieren oder um Informationen &uuml;ber uns anzubieten.</p>
<p>Wir weisen darauf hin, dass dabei Daten der Nutzer au&szlig;erhalb des Raumes der Europ&auml;ischen Union verarbeitet werden k&ouml;nnen. Hierdurch k&ouml;nnen sich f&uuml;r die Nutzer Risiken ergeben, weil so z.B. die Durchsetzung der Rechte der Nutzer erschwert werden k&ouml;nnte. Im Hinblick auf US-Anbieter, die unter dem Privacy-Shield zertifiziert sind oder vergleichbare Garantien eines sicheren Datenschutzniveaus bieten, weisen wir darauf hin, dass sie sich damit verpflichten, die Datenschutzstandards der EU einzuhalten.</p>
<p>Ferner werden die Daten der Nutzer innerhalb sozialer Netzwerke im Regelfall f&uuml;r Marktforschungs- und Werbezwecke verarbeitet. So k&ouml;nnen z.B. anhand des Nutzungsverhaltens und sich daraus ergebender Interessen der Nutzer Nutzungsprofile erstellt werden. Die Nutzungsprofile k&ouml;nnen wiederum verwendet werden, um z.B. Werbeanzeigen innerhalb und au&szlig;erhalb der Netzwerke zu schalten, die mutma&szlig;lich den Interessen der Nutzer entsprechen. Zu diesen Zwecken werden im Regelfall Cookies auf den Rechnern der Nutzer gespeichert, in denen das Nutzungsverhalten und die Interessen der Nutzer gespeichert werden. Ferner k&ouml;nnen in den Nutzungsprofilen auch Daten unabh&auml;ngig der von den Nutzern verwendeten Ger&auml;te gespeichert werden (insbesondere, wenn die Nutzer Mitglieder der jeweiligen Plattformen sind und bei diesen eingeloggt sind).</p>
<p>F&uuml;r eine detaillierte Darstellung der jeweiligen Verarbeitungsformen und der Widerspruchsm&ouml;glichkeiten (Opt-Out) verweisen wir auf die Datenschutzerkl&auml;rungen und Angaben der Betreiber der jeweiligen Netzwerke.</p>
<p>Auch im Fall von Auskunftsanfragen und der Geltendmachung von Betroffenenrechten weisen wir darauf hin, dass diese am effektivsten bei den Anbietern geltend gemacht werden k&ouml;nnen. Nur die Anbieter haben jeweils Zugriff auf die Daten der Nutzer und k&ouml;nnen direkt entsprechende Ma&szlig;nahmen ergreifen und Ausk&uuml;nfte geben. Sollten Sie dennoch Hilfe ben&ouml;tigen, dann k&ouml;nnen Sie sich an uns wenden.</p>
<ul>
<li>Verarbeitete Datenarten:&nbsp;Bestandsdaten (z.B. Namen, Adressen), Kontaktdaten (z.B. E-Mail, Telefonnummern), Inhaltsdaten (z.B. Texteingaben, Fotografien, Videos), Nutzungsdaten (z.B. besuchte Webseiten, Interesse an Inhalten, Zugriffszeiten), Meta-/Kommunikationsdaten (z.B. Ger&auml;te-Informationen, IP-Adressen).</li>
<li>Betroffene Personen:&nbsp;Nutzer (z.B. Webseitenbesucher, Nutzer von Onlinediensten).</li>
<li>Zwecke der Verarbeitung:&nbsp;Kontaktanfragen und Kommunikation, Tracking (z.B. interessens-/verhaltensbezogenes Profiling, Nutzung von Cookies), Remarketing, Reichweitenmessung (z.B. Zugriffsstatistiken, Erkennung wiederkehrender Besucher).</li>
<li>Rechtsgrundlagen:&nbsp;Berechtigte Interessen (Art. 6 Abs. 1 S. 1 lit. f.&nbsp;DSGVO).</li>
</ul>
<p>Eingesetzte Dienste und Diensteanbieter:</p>
<ul>
<li>Facebook:&nbsp;Soziales Netzwerk; Dienstanbieter: Facebook Ireland Ltd., 4 Grand Canal Square, Grand Canal Harbour, Dublin 2, Irland, Mutterunternehmen: Facebook, 1 Hacker Way, Menlo Park, CA 94025, USA; Website:<a href="https://www.google.com/url?q=https://www.facebook.com/&amp;sa=D&amp;ust=1584885756544000">https://www.facebook.com</a>; Datenschutzerkl&auml;rung:<a href="https://www.google.com/url?q=https://www.facebook.com/about/privacy&amp;sa=D&amp;ust=1584885756545000">https://www.facebook.com/about/privacy</a>; Privacy Shield (Gew&auml;hrleistung Datenschutzniveau bei Verarbeitung von Daten in den USA):<a href="https://www.google.com/url?q=https://www.privacyshield.gov/participant?id%3Da2zt0000000GnywAAC%26status%3DActive&amp;sa=D&amp;ust=1584885756545000">https://www.privacyshield.gov/participant?id=a2zt0000000GnywAAC&amp;status=Active</a>; Widerspruchsm&ouml;glichkeit (Opt-Out): Einstellungen f&uuml;r Werbeanzeigen:<a href="https://www.google.com/url?q=https://www.facebook.com/settings?tab%3Dads&amp;sa=D&amp;ust=1584885756545000">https://www.facebook.com/settings?tab=ads</a>; Zus&auml;tzliche Hinweise zum Datenschutz: Vereinbarung &uuml;ber gemeinsame Verarbeitung personenbezogener Daten auf Facebook-Seiten:<a href="https://www.google.com/url?q=https://www.facebook.com/legal/terms/page_controller_addendum&amp;sa=D&amp;ust=1584885756546000">https://www.facebook.com/legal/terms/page_controller_addendum</a>, Datenschutzhinweise f&uuml;r Facebook-Seiten:<a href="https://www.google.com/url?q=https://www.facebook.com/legal/terms/information_about_page_insights_data&amp;sa=D&amp;ust=1584885756546000">https://www.facebook.com/legal/terms/information_about_page_insights_data</a>.</li>
<li>LinkedIn:&nbsp;Soziales Netzwerk; Dienstanbieter: LinkedIn Ireland Unlimited Company, Wilton Place, Dublin 2, Irland; Website:<a href="https://www.google.com/url?q=https://www.linkedin.com/&amp;sa=D&amp;ust=1584885756547000">https://www.linkedin.com</a>; Datenschutzerkl&auml;rung:<a href="https://www.google.com/url?q=https://www.linkedin.com/legal/privacy-policy&amp;sa=D&amp;ust=1584885756547000">https://www.linkedin.com/legal/privacy-policy</a>; Privacy Shield (Gew&auml;hrleistung Datenschutzniveau bei Verarbeitung von Daten in den USA):<a href="https://www.google.com/url?q=https://www.privacyshield.gov/participant?id%3Da2zt0000000L0UZAA0%26status%3DActive&amp;sa=D&amp;ust=1584885756547000">https://www.privacyshield.gov/participant?id=a2zt0000000L0UZAA0&amp;status=Active</a>; Widerspruchsm&ouml;glichkeit (Opt-Out):<a href="https://www.google.com/url?q=https://www.linkedin.com/psettings/guest-controls/retargeting-opt-out&amp;sa=D&amp;ust=1584885756548000">https://www.linkedin.com/psettings/guest-controls/retargeting-opt-out</a>.</li>
<li>Twitter:&nbsp;Soziales Netzwerk; Dienstanbieter: Twitter Inc., 1355 Market Street, Suite 900, San Francisco, CA 94103, USA; Datenschutzerkl&auml;rung:<a href="https://www.google.com/url?q=https://twitter.com/de/privacy&amp;sa=D&amp;ust=1584885756548000">https://twitter.com/de/privacy</a>, (Einstellungen)<a href="https://www.google.com/url?q=https://twitter.com/personalization&amp;sa=D&amp;ust=1584885756548000">https://twitter.com/personalization</a>; Privacy Shield (Gew&auml;hrleistung Datenschutzniveau bei Verarbeitung von Daten in den USA):<a href="https://www.google.com/url?q=https://www.privacyshield.gov/participant?id%3Da2zt0000000TORzAAO%26status%3DActive&amp;sa=D&amp;ust=1584885756549000">https://www.privacyshield.gov/participant?id=a2zt0000000TORzAAO&amp;status=Active</a>.</li>
</ul>
<h2>Plugins und eingebettete Funktionen sowie Inhalte</h2>
<p>Wir binden in unser Onlineangebot Funktions- und Inhaltselemente ein, die von den Servern ihrer jeweiligen Anbieter (nachfolgend bezeichnet als "Drittanbieter&ldquo;) bezogen werden. Dabei kann es sich zum Beispiel um Grafiken, Videos oder Social-Media-Schaltfl&auml;chen sowie Beitr&auml;ge handeln (nachfolgend einheitlich bezeichnet als "Inhalte&rdquo;).</p>
<p>Die Einbindung setzt immer voraus, dass die Drittanbieter dieser Inhalte die IP-Adresse der Nutzer verarbeiten, da sie ohne die IP-Adresse die Inhalte nicht an deren Browser senden k&ouml;nnten. Die IP-Adresse ist damit f&uuml;r die Darstellung dieser Inhalte oder Funktionen erforderlich. Wir bem&uuml;hen uns, nur solche Inhalte zu verwenden, deren jeweilige Anbieter die IP-Adresse lediglich zur Auslieferung der Inhalte verwenden. Drittanbieter k&ouml;nnen ferner sogenannte Pixel-Tags (unsichtbare Grafiken, auch als "Web Beacons" bezeichnet) f&uuml;r statistische oder Marketingzwecke verwenden. Durch die "Pixel-Tags" k&ouml;nnen Informationen, wie der Besucherverkehr auf den Seiten dieser Webseite, ausgewertet werden. Die pseudonymen Informationen k&ouml;nnen ferner in Cookies auf dem Ger&auml;t der Nutzer gespeichert werden und unter anderem technische Informationen zum Browser und zum Betriebssystem, zu verweisenden Webseiten, zur Besuchszeit sowie weitere Angaben zur Nutzung unseres Onlineangebotes enthalten als auch mit solchen Informationen aus anderen Quellen verbunden werden.</p>
<p>Hinweise zu Rechtsgrundlagen:&nbsp;Sofern wir die Nutzer um deren Einwilligung in den Einsatz der Drittanbieter bitten, ist die Rechtsgrundlage der Verarbeitung von Daten die Einwilligung. Ansonsten werden die Daten der Nutzer auf Grundlage unserer berechtigten Interessen (d.h. Interesse an effizienten, wirtschaftlichen und empf&auml;ngerfreundlichen Leistungen) verarbeitet. In diesem Zusammenhang m&ouml;chten wir Sie auch auf die Informationen zur Verwendung von Cookies in dieser Datenschutzerkl&auml;rung hinweisen.</p>
<ul>
<li>Verarbeitete Datenarten:&nbsp;Nutzungsdaten (z.B. besuchte Webseiten, Interesse an Inhalten, Zugriffszeiten), Meta-/Kommunikationsdaten (z.B. Ger&auml;te-Informationen, IP-Adressen), Bestandsdaten (z.B. Namen, Adressen), Kontaktdaten (z.B. E-Mail, Telefonnummern), Inhaltsdaten (z.B. Texteingaben, Fotografien, Videos).</li>
<li>Betroffene Personen:&nbsp;Nutzer (z.B. Webseitenbesucher, Nutzer von Onlinediensten).</li>
<li>Zwecke der Verarbeitung:&nbsp;Bereitstellung unseres Onlineangebotes und Nutzerfreundlichkeit, Vertragliche Leistungen und Service, Sicherheitsma&szlig;nahmen, Verwaltung und Beantwortung von Anfragen.</li>
<li>Rechtsgrundlagen:&nbsp;Einwilligung (Art. 6 Abs. 1 S. 1 lit. a DSGVO), Vertragserf&uuml;llung und vorvertragliche Anfragen (Art. 6 Abs. 1 S. 1 lit. b. DSGVO), Berechtigte Interessen (Art. 6 Abs. 1 S. 1 lit. f.&nbsp;DSGVO).</li>
</ul>
<p>Eingesetzte Dienste und Diensteanbieter:</p>
<ul>
<li>YouTube-Videos:&nbsp;Videoinhalte; Dienstanbieter: Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Irland, Mutterunternehmen: Google LLC, 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA; Website:<a href="https://www.google.com/url?q=https://www.youtube.com/&amp;sa=D&amp;ust=1584885756550000">https://www.youtube.com</a>; Datenschutzerkl&auml;rung:<a href="https://www.google.com/url?q=https://policies.google.com/privacy&amp;sa=D&amp;ust=1584885756551000">https://policies.google.com/privacy</a>; Privacy Shield (Gew&auml;hrleistung Datenschutzniveau bei Verarbeitung von Daten in den USA):<a href="https://www.google.com/url?q=https://www.privacyshield.gov/participant?id%3Da2zt000000001L5AAI%26status%3DActive&amp;sa=D&amp;ust=1584885756551000">https://www.privacyshield.gov/participant?id=a2zt000000001L5AAI&amp;status=Active</a>; Widerspruchsm&ouml;glichkeit (Opt-Out): Opt-Out-Plugin:<a href="https://www.google.com/url?q=https://tools.google.com/dlpage/gaoptout?hl%3Dde&amp;sa=D&amp;ust=1584885756551000">https://tools.google.com/dlpage/gaoptout?hl=de</a>, Einstellungen f&uuml;r die Darstellung von Werbeeinblendungen:<a href="https://www.google.com/url?q=https://adssettings.google.com/authenticated&amp;sa=D&amp;ust=1584885756551000">https://adssettings.google.com/authenticated</a>.</li>
</ul>
<h2>&Auml;nderung und Aktualisierung der Datenschutzerkl&auml;rung</h2>
<p>Wir bitten Sie, sich regelm&auml;&szlig;ig &uuml;ber den Inhalt unserer Datenschutzerkl&auml;rung zu informieren. Wir passen die Datenschutzerkl&auml;rung an, sobald die &Auml;nderungen der von uns durchgef&uuml;hrten Datenverarbeitungen dies erforderlich machen. Wir informieren Sie, sobald durch die &Auml;nderungen eine Mitwirkungshandlung Ihrerseits (z.B. Einwilligung) oder eine sonstige individuelle Benachrichtigung erforderlich wird.</p>
<p>Sofern wir in dieser Datenschutzerkl&auml;rung Adressen und Kontaktinformationen von Unternehmen und Organisationen angeben, bitten wir zu beachten, dass die Adressen sich &uuml;ber die Zeit &auml;ndern k&ouml;nnen und bitten die Angaben vor Kontaktaufnahme zu pr&uuml;fen.</p>
<h2>Rechte der betroffenen Personen</h2>
<p>Ihnen stehen als Betroffene nach der DSGVO verschiedene Rechte zu, die sich insbesondere aus Art. 15 bis 18 und 21 DSGVO ergeben:</p>
<ul>
<li>Widerspruchsrecht: Sie haben das Recht, aus Gr&uuml;nden, die sich aus Ihrer besonderen Situation ergeben, jederzeit gegen die Verarbeitung der Sie betreffenden personenbezogenen Daten, die aufgrund von Art. 6 Abs. 1 lit. e oder f DSGVO erfolgt, Widerspruch einzulegen; dies gilt auch f&uuml;r ein auf diese Bestimmungen gest&uuml;tztes Profiling. Werden die Sie betreffenden personenbezogenen Daten verarbeitet, um Direktwerbung zu betreiben, haben Sie das Recht, jederzeit Widerspruch gegen die Verarbeitung der Sie betreffenden personenbezogenen Daten zum Zwecke derartiger Werbung einzulegen; dies gilt auch f&uuml;r das Profiling, soweit es mit solcher Direktwerbung in Verbindung steht.</li>
<li>Widerrufsrecht bei Einwilligungen:&nbsp;Sie haben das Recht, erteilte Einwilligungen jederzeit zu widerrufen.</li>
<li>Auskunftsrecht:&nbsp;Sie haben das Recht, eine Best&auml;tigung dar&uuml;ber zu verlangen, ob betreffende Daten verarbeitet werden und auf Auskunft &uuml;ber diese Daten sowie auf weitere Informationen und Kopie der Daten entsprechend den gesetzlichen Vorgaben.</li>
<li>Recht auf Berichtigung:&nbsp;Sie haben entsprechend den gesetzlichen Vorgaben das Recht, die Vervollst&auml;ndigung der Sie betreffenden Daten oder die Berichtigung der Sie betreffenden unrichtigen Daten zu verlangen.</li>
<li>Recht auf L&ouml;schung und Einschr&auml;nkung der Verarbeitung:&nbsp;Sie haben nach Ma&szlig;gabe der gesetzlichen Vorgaben das Recht, zu verlangen, dass Sie betreffende Daten unverz&uuml;glich gel&ouml;scht werden, bzw. alternativ nach Ma&szlig;gabe der gesetzlichen Vorgaben eine Einschr&auml;nkung der Verarbeitung der Daten zu verlangen.</li>
<li>Recht auf Daten&uuml;bertragbarkeit:&nbsp;Sie haben das Recht, Sie betreffende Daten, die Sie uns bereitgestellt haben, nach Ma&szlig;gabe der gesetzlichen Vorgaben in einem strukturierten, g&auml;ngigen und maschinenlesbaren Format zu erhalten oder deren &Uuml;bermittlung an einen anderen Verantwortlichen zu fordern.</li>
<li>Beschwerde bei Aufsichtsbeh&ouml;rde:&nbsp;Sie haben ferner nach Ma&szlig;gabe der gesetzlichen Vorgaben das Recht, bei einer Aufsichtsbeh&ouml;rde, insbesondere in dem Mitgliedstaat Ihres gew&ouml;hnlichen Aufenthaltsorts, Ihres Arbeitsplatzes oder des Orts des mutma&szlig;lichen Versto&szlig;es Beschwerde einzulegen, wenn Sie der Ansicht sind, dass die Verarbeitung der Sie betreffenden personenbezogenen Daten gegen die DSGVO verst&ouml;&szlig;t.</li>
</ul>
<h2>Begriffsdefinitionen</h2>
<p>In diesem Abschnitt erhalten Sie eine &Uuml;bersicht &uuml;ber die in dieser Datenschutzerkl&auml;rung verwendeten Begrifflichkeiten. Viele der Begriffe sind dem Gesetz entnommen und vor allem im Art. 4 DSGVO definiert. Die gesetzlichen Definitionen sind verbindlich. Die nachfolgenden Erl&auml;uterungen sollen dagegen vor allem dem Verst&auml;ndnis dienen. Die Begriffe sind alphabetisch sortiert.</p>
<ul>
<li>Besuchsaktionsauswertung:&nbsp;"Besuchsaktionsauswertung" (englisch "Conversion Tracking") bezeichnet ein Verfahren, mit dem die Wirksamkeit von Marketingma&szlig;nahmen festgestellt werden kann. Dazu wird im Regelfall ein Cookie auf den Ger&auml;ten der Nutzer innerhalb der Webseiten, auf denen die Marketingma&szlig;nahmen erfolgen, gespeichert und dann erneut auf der Zielwebseite abgerufen. Beispielsweise k&ouml;nnen wir so nachvollziehen, ob die von uns auf anderen Webseiten geschalteten Anzeigen erfolgreich waren).</li>
<li>IP-Masking:&nbsp;Als "IP-Masking" wird eine Methode bezeichnet, bei der das letzte Oktett, d.h., die letzten beiden Zahlen einer IP-Adresse, gel&ouml;scht wird, damit die IP-Adresse nicht mehr der eindeutigen Identifizierung einer Person dienen kann. Daher ist das IP-Masking ein Mittel zur Pseudonymisierung von Verarbeitungsverfahren, insbesondere im Onlinemarketing</li>
<li>Interessenbasiertes und verhaltensbezogenes Marketing:&nbsp;Von interessens- und/oder verhaltensbezogenem Marketing spricht man, wenn potentielle Interessen von Nutzern an Anzeigen und sonstigen Inhalten m&ouml;glichst genau vorbestimmt werden. Dies geschieht anhand von Angaben zu deren Vorverhalten (z.B. Aufsuchen von bestimmten Webseiten und Verweilen auf diesen, Kaufverhaltens oder Interaktion mit anderen Nutzern), die in einem sogenannten Profil gespeichert werden. Zu diesen Zwecken werden im Regelfall Cookies eingesetzt.</li>
<li>Konversionsmessung:&nbsp;Die Konversionsmessung ist ein Verfahren, mit dem die Wirksamkeit von Marketingma&szlig;nahmen festgestellt werden kann. Dazu wird im Regelfall ein Cookie auf den Ger&auml;ten der Nutzer innerhalb der Webseiten, auf denen die Marketingma&szlig;nahmen erfolgen, gespeichert und dann erneut auf der Zielwebseite abgerufen. Beispielsweise k&ouml;nnen wir so nachvollziehen, ob die von uns auf anderen Webseiten geschalteten Anzeigen erfolgreich waren.</li>
<li>Personenbezogene Daten:&nbsp;"Personenbezogene Daten" sind alle Informationen, die sich auf eine identifizierte oder identifizierbare nat&uuml;rliche Person (im Folgenden "betroffene Person") beziehen; als identifizierbar wird eine nat&uuml;rliche Person angesehen, die direkt oder indirekt, insbesondere mittels Zuordnung zu einer Kennung wie einem Namen, zu einer Kennnummer, zu Standortdaten, zu einer Online-Kennung (z.B. Cookie) oder zu einem oder mehreren besonderen Merkmalen identifiziert werden kann, die Ausdruck der physischen, physiologischen, genetischen, psychischen, wirtschaftlichen, kulturellen oder sozialen Identit&auml;t dieser nat&uuml;rlichen Person sind.</li>
<li>Profiling:&nbsp;Als "Profiling" wird jede Art der automatisierten Verarbeitung personenbezogener Daten bezeichnet, die darin besteht, dass diese personenbezogenen Daten verwendet werden, um bestimmte pers&ouml;nliche Aspekte, die sich auf eine nat&uuml;rliche Person beziehen (je nach Art des Profilings geh&ouml;ren dazu Informationen betreffend das Alter, das Geschlecht, Standortdaten und Bewegungsdaten, Interaktion mit Webseiten und deren Inhalten, Einkaufsverhalten, soziale Interaktionen mit anderen Menschen) zu analysieren, zu bewerten oder, um sie vorherzusagen (z.B. die Interessen an bestimmten Inhalten oder Produkten, das Klickverhalten auf einer Webseite oder den Aufenthaltsort). Zu Zwecken des Profilings werden h&auml;ufig Cookies und Web-Beacons eingesetzt.</li>
<li>Reichweitenmessung:&nbsp;Die Reichweitenmessung (auch als Web Analytics bezeichnet) dient der Auswertung der Besucherstr&ouml;me eines Onlineangebotes und kann das Verhalten oder Interessen der Besucher an bestimmten Informationen, wie z.B. Inhalten von Webseiten, umfassen. Mit Hilfe der Reichweitenanalyse k&ouml;nnen Webseiteninhaber z.B. erkennen, zu welcher Zeit Besucher ihre Webseite besuchen und f&uuml;r welche Inhalte sie sich interessieren. Dadurch k&ouml;nnen sie z.B. die Inhalte der Webseite besser an die Bed&uuml;rfnisse ihrer Besucher anpassen. Zu Zwecken der Reichweitenanalyse werden h&auml;ufig pseudonyme Cookies und Web-Beacons eingesetzt, um wiederkehrende Besucher zu erkennen und so genauere Analysen zur Nutzung eines Onlineangebotes zu erhalten.</li>
<li>Remarketing:&nbsp;Vom "Remarketing" bzw. "Retargeting" spricht man, wenn z.B. zu Werbezwecken vermerkt wird, f&uuml;r welche Produkte sich ein Nutzer auf einer Webseite interessiert hat, um den Nutzer auf anderen Webseiten an diese Produkte, z.B. in Werbeanzeigen, zu erinnern.</li>
<li>Tracking:&nbsp;Vom "Tracking" spricht man, wenn das Verhalten von Nutzern &uuml;ber mehrere Onlineangebote hinweg nachvollzogen werden kann. Im Regelfall werden im Hinblick auf die genutzten Onlineangebote Verhaltens- und Interessensinformationen in Cookies oder auf Servern der Anbieter der Trackingtechnologien gespeichert (sogenanntes Profiling). Diese Informationen k&ouml;nnen anschlie&szlig;end z.B. eingesetzt werden, um den Nutzern Werbeanzeigen anzuzeigen, die voraussichtlich deren Interessen entsprechen.</li>
<li>Verantwortlicher:&nbsp;Als "Verantwortlicher" wird die nat&uuml;rliche oder juristische Person, Beh&ouml;rde, Einrichtung oder andere Stelle, die allein oder gemeinsam mit anderen &uuml;ber die Zwecke und Mittel der Verarbeitung von personenbezogenen Daten entscheidet, bezeichnet.</li>
<li>Verarbeitung:&nbsp;"Verarbeitung" ist jeder mit oder ohne Hilfe automatisierter Verfahren ausgef&uuml;hrte Vorgang oder jede solche Vorgangsreihe im Zusammenhang mit personenbezogenen Daten. Der Begriff reicht weit und umfasst praktisch jeden Umgang mit Daten, sei es das Erheben, das Auswerten, das Speichern, das &Uuml;bermitteln oder das L&ouml;schen.</li>
</ul>
<p><a href="https://www.google.com/url?q=https://datenschutz-generator.de/?l%3Dde&amp;sa=D&amp;ust=1584885756556000">Erstellt mit kostenlosem Datenschutz-Generator.de von Dr.&nbsp;Thomas Schwenke</a></p>


</div>
</template>

<script>
export default {
    
}
</script>

<style>
    .content {
        text-align: left;
    }
</style>